seed: 0
env_name: "ALE/NameThisGame-v5"
dqn_pro: False

timesteps_per_epoch: 1
batch_size: 32
total_steps: 3000000
decay_steps: 250000
lr: 1e-4
c_value: 0.2
gamma: 0.99

init_epsilon: 1
final_epsilon: 0.01
eval_epsilon: 0.001

loss_freq: 50
refresh_target_network_freq: 8000
eval_freq: 10000

max_grad_norm: 50

n_eval_episodes: 2
max_steps_per_episode: 27000

replay_buffer_size: 50000
min_replay_buffer_size: 10000